Maybe python2 will work better?
*sigh* I'm too lazy to look this up right now:

botocore.exceptions.ClientError: An error occurred (IncompleteSignature) 
when calling the ListHostedZones operation: 
'***/20200304/us-east-1/route53/aws4_request' not a valid key=value pair 
(missing equal-sign) in Authorization header: 'AWS4-HMAC-SHA256 
Credential= ***/20200304/us-east-1/route53/aws4_request, 
SignedHeaders=host;x-amz-date, Signature=FOO'.